databases:
  - name: optigest_db
    plan: free
    databaseName: optigest
    user: optigest

services:
  - type: web
    plan: free
    name: optigest
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: optigest_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4